# Generated by Django on 2025-10-15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0054_add_brin_index_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="import_tags",
            field=models.JSONField(
                default=list,
                null=True,
                blank=True,
                verbose_name="import tags",
                help_text=(
                    "Tags applied to this task during import (e.g. batch or experiment identifiers)"
                ),
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="import_batch_id",
            field=models.CharField(
                max_length=255,
                null=True,
                blank=True,
                verbose_name="import batch id",
                help_text="Batch identifier assigned during import to group tasks",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="import_source",
            field=models.CharField(
                max_length=255,
                null=True,
                blank=True,
                verbose_name="import source",
                help_text="Source of import: ui, api, storage, etc.",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["import_batch_id"], name="task_import_batch_idx"),
        ),
    ]

