# Generated by Django 5.1.10 on 2025-11-05 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0058_merge_20251105_0000"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="task",
            new_name="task_import__467338_idx",
            old_name="task_import_batch_idx",
        ),
    ]
