title: SAM2 – Interactive Segmentation
type: community
group: BioWork
image: /static/templates/semantic-segmentation-with-masks.png
order: 3
config: |
  <View style="display: flex;">
  <!-- Left side: Image -->
  <View style="flex: 80%; margin-right: 1em">
    <Image name="image" value="$image" zoom="true"/>
  </View>
  
  <!-- Right side: All labeling tools -->
  <View style="flex: 20%;">
    <!-- Smart Keypoint Labels (tag3) -->
    <Header value="Keypoint Labels"/>
    <KeyPointLabels name="tag3" toName="image" smart="true">
      <Label value="Object" background="#0000FF" showInline="true" />
    </KeyPointLabels>
    
    <!-- Smart Rectangle Labels (tag4) -->
    <Header value="Rectangle Labels"/>
    <RectangleLabels name="tag4" toName="image" smart="true">
      <Label value="Object" smart="true" background="#0000FF"/>
    </RectangleLabels>
    
    <TextArea name="mean_intensity" toName="image"
              perRegion="true"
              rows="5"
              placeholder="Mean Intensity"
              displayMode="region-list"
              />
    
    <!-- Brush Labels (tag1) -->
    <Header value="Result: Brush Labels"/>
    <BrushLabels name="tag1" toName="image">
      <Label value="Object" background="#FF0000"/>
    </BrushLabels>

  </View>
  </View>

ml_backends:
  - url: http://sam2-backend:9090
    title: SAM2
    is_interactive: true
    extra_params:
      SAM_PREANNOTATE: 0


