# Generated by Django 5.1.10 on 2025-11-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_userproducttour"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_premium",
            field=models.BooleanField(
                default=False, verbose_name="premium subscription"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="stripe_customer_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="stripe customer id"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="stripe_subscription_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="stripe subscription id",
            ),
        ),
    ]
