# Generated by Django 5.1.10 on 2025-08-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0006_alter_organizationmember_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmember',
            name='joined_via_invitation',
            field=models.BooleanField(
                default=False,
                help_text='Whether this user joined via an invitation link'
            ),
        ),
    ]
